version: "3"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: production
    command: yarn start:api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - 3333:3333
    networks:
      - shared-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: production
    command: yarn start:web
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - 4200:4200
    networks:
      - shared-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: aafiyah
    ports:
      - 5454:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  postgres-data:

networks:
  shared-network:
    driver: bridge