export const metaKeywords = [
  "Islamic e-commerce",
  "Islamic products",
  "Halal online shop",
  "Muslim fashion",
  "Islamic clothing",
  "Islamic books",
  "Islamic gifts",
  "Islamic home decor",
  "Islamic art",
  "Islamic jewelry",
  "Modest fashion",
  "Abayas",
  "Hijabs",
  "Prayer mats",
  "Quran",
  "Islamic calligraphy",
  "Islamic accessories",
  "Islamic toys",
  "Islamic stationery",
  "Islamic stationery",
  "Islamic calendars",
  "Islamic lifestyle",
  "Islamic teachings",
  "Islamic reminders",
  "Islamic spirituality",
  "Islamic wellness",
  "Ramadan products",
  "Eid gifts",
  "Islamic wedding gifts",
  "Islamic baby products",
  "Islamic parenting",
  "Islamic education",
  "Islamic charity",
  "Islamic community",
  "Islamic events",
  "Islamic festivals",
  "Islamic holidays",
  "Muslim home essentials",
  "Islamic kitchenware",
  "Islamic bath essentials",
  "Islamic healthcare",
  "Islamic finance",
  "Islamic investment",
  "Islamic banking",
  "Islamic insurance",
  "Islamic personal care",
  "Islamic skincare",
  "Islamic fragrances",
  "Islamic books for kids",
  "Islamic apps",
  "Islamic technology",
  "Islamic entrepreneurship",
  "Islamic entrepreneurship",
  "Islamic marketing",
  "Islamic business",
  "Islamic ethics",
  "Islamic fashion trends",
  "Islamic modesty",
  "Islamic modesty fashion",
  "Islamic modesty tips",
  "Islamic modesty guidelines",
  "Islamic fashion influencers",
  "Islamic fashion bloggers",
  "Islamic fashion brands",
  "Islamic fashion designers",
  "Islamic fashion inspiration",
  "Islamic fashion for women",
  "Islamic fashion for men",
  "Islamic fashion for kids",
  "Islamic fashion for teens",
  "Islamic fashion for hijabis",
  "Islamic fashion for abayas",
  "Islamic fashion for jilbabs",
  "Islamic fashion for niqabs",
  "Islamic fashion for burkinis",
  "Islamic fashion for thobes",
  "Islamic fashion for kufis",
  "Islamic fashion for turbans",
  "Islamic fashion for accessories",
  "Islamic fashion for jewelry",
  "Islamic fashion for footwear",
  "Islamic fashion for bags",
  "Islamic fashion for watches",
  "Islamic fashion for sunglasses",
  "Islamic fashion for perfumes",
  "Islamic fashion for cosmetics",
  "Islamic fashion for health",
  "Islamic fashion for wellness",
  "Islamic fashion for fitness",
  "Islamic fashion for sports",
  "Islamic fashion for outdoor",
  "Islamic fashion for travel",
  "Islamic fashion for occasions",
  "Islamic fashion for weddings",
  "Islamic fashion for parties",
  "Islamic fashion for Eid",
  "Islamic fashion for Ramadan",
  "Islamic fashion for Umrah",
  "Islamic fashion for Hajj",
  "Islamic fashion for Islamic events",
  "Islamic fashion for cultural events",
  "Islamic fashion for formal events",
  "Islamic fashion for casual events",
  "Islamic fashion for everyday wear"
];
